export const delMsgAction = 'DELETE_MESSAGE'
export const repMsgAction = 'REPLY'
export const readMsgAction = 'READ_MESSAGE'
export const getMsgsAction = 'GET_MESSAGES'
export const newErrAction = 'NEW_ERROR'
export const closeErrAction = 'CLOSE_ERROR'
